apiVersion: v1
kind: Service
metadata:
  name: kube-dash-nodeport
spec:
  selector:
    app: kube-dash
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000  # Choose a port in the range 30000-32767
